name: po2
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - beautifulsoup4=4.9.3
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=4.0.0
  - cryptography=3.3.1
  - curl=7.67.0
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.0.2
  - geos=3.8.0
  - geotiff=1.5.1
  - giflib=5.1.4
  - glib=2.63.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.2
  - jpeg=9b
  - json-c=0.13.1
  - kealib=1.4.7
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libcurl=7.67.0
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=3.0.2
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openjpeg=2.3.0
  - openssl=1.1.1i
  - pcre=8.44
  - pip=20.3.3
  - pixman=0.40.0
  - poppler=0.65.0
  - poppler-data=0.4.10
  - postgresql=11.2
  - proj=6.2.1
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.2
  - readline=7.0
  - requests=2.25.1
  - setuptools=52.0.0
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.33.0
  - tbb=2018.0.5
  - tiledb=1.6.3
  - tk=8.6.10
  - urllib3=1.26.3
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
