name: po2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blas=1.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2024.2.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cfitsio=3.470
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.1
  - curl=7.77.0
  - cycler=0.10.0
  - debugpy=1.4.1
  - decorator=5.1.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.4.1
  - fiona=1.8.20
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.1
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - intel-openmp=2021.3.0
  - ipykernel=6.20.2
  - ipython=8.18.1
  - jbig=2.1
  - jedi=0.19.1
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - jupyter_client=7.1.2
  - jupyter_core=5.7.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.3.1
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.6
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munch=2.5.0
  - ncurses=6.2
  - nest-asyncio=1.6.0
  - networkx=2.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=23.2
  - pandas=1.3.1
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.1.3
  - pixman=0.40.0
  - platformdirs=4.2.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=8.0.1
  - prompt-toolkit=3.0.42
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=2.4.7
  - pyproj=3.1.0
  - python=3.9.5
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=22.1.0
  - readline=8.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - setuptools=52.0.0
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.36.0
  - stack_data=0.6.2
  - threadpoolctl=3.0.0
  - tiledb=2.3.2
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzcode=2021a
  - tzdata=2021a
  - wcwidth=0.2.13
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
      - altair==5.2.0
      - attrs==23.2.0
      - branca==0.7.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colorlog==6.8.2
      - colormap==1.0.6
      - dask==2024.1.1
      - descartes==1.1.0
      - easydev==0.12.1
      - folium==0.15.1
      - fsspec==2023.12.2
      - geojson==3.1.0
      - geovoronoi==0.4.0
      - h3==3.7.6
      - idna==3.6
      - importlib-metadata==7.0.1
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - locket==1.0.0
      - markupsafe==2.1.5
      - networkit==11.0
      - numpy==1.22.4
      - partd==1.4.1
      - pyyaml==6.0.1
      - referencing==0.33.0
      - requests==2.31.0
      - rpds-py==0.17.1
      - seaborn==0.13.2
      - toolz==0.12.1
      - tqdm==4.66.1
      - urllib3==2.2.0
      - xyzservices==2023.10.1
      - zipp==3.17.0
